apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_HOST: "postgres" # Using postgres service name so that it can find that service
  DB_PORT: "5432"
  DB_USER: "guestbookuser"
  DB_NAME: "guestbookdatabase"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"