name: Guestbook CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Dependencies
        run: make -C backend deps

      - name: Run Backend Tests
        run: make -C backend test
        env:
          # Mapping your Secrets/Vars to the test environment
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_USER: ${{ vars.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ vars.DB_NAME }}
          REDIS_HOST: ${{ vars.REDIS_HOST }}
          REDIS_PORT: ${{ vars.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          PORT: ${{ vars.PORT }}

  build-images:
    needs: backend-tests  # Only build if tests pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Backend Image
        run: |
             podman build -t guestbook-backend:latest ./backend
             podman save -o backend.tar guestbook-backend:latest ./backend
             

      - name: Scan Backend Image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          input: 'backend.tar'
          image-ref: 'guestbook-backend:latest'
          format: 'table'
          exit-code: '0' 
          severity: 'CRITICAL,HIGH'

      - name: Build Frontend Image
        run: |
             podman build -t guestbook-frontend:latest ./frontend
             podman save -o frontend.tar guestbook-frontend:latest ./frontend

      - name: Scan Backend Image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          input: 'frontend.tar'
          image-ref: 'guestbook-frontend:latest'
          format: 'table'
          exit-code: '0' 
          severity: 'CRITICAL,HIGH'

      - name: Log in to Quay.io
        run: podman login -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }} quay.io

      - name: Push Images to Quay
        run: |
          # Tag and push Backend
          podman tag guestbook-backend:latest quay.io/shaheeramudasar/guestbook-backend:latest
          podman push quay.io/YOUR_QUAY_USER/guestbook-backend:latest
          
          # Tag and push Frontend
          podman tag guestbook-frontend:latest quay.io/shaheeramudasar/guestbook-frontend:latest
          podman push quay.io/YOUR_QUAY_USER/guestbook-frontend:latest

      